version: "3.8"

services:
  db:
    container_name: db
    image: postgres:17
    environment:
      POSTGRES_DB: northwind
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgresql_data:/var/lib/postgresql/data
      - ./northwind.sql:/docker-entrypoint-initdb.d/northwind.sql:ro
      - ./files:/files
    ports:
      - "55432:5432"
    networks:
      - db
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: postgres
      PGADMIN_LISTEN_PORT: 5050
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin_root_prefs:/var/lib/pgadmin
      - ./files:/files
    ports:
      - "5050:5050"
    networks:
      - db
    depends_on:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  postgresql_data:
    driver: local
  pgadmin_root_prefs:
    driver: local
